'use strict';

const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { validateCourse } = require('./lib/manifest-schema');

const templateRoot = path.join(__dirname, '..');
const runtimeRoot = path.join(templateRoot, 'app');
const repositoryRoot = path.join(templateRoot, '..');
const generatedRoot = path.join(repositoryRoot, 'courses');
const catalogPath = path.join(repositoryRoot, 'courses.yaml');
const reportPath = path.join(templateRoot, 'tests', 'generated', 'course-factory-report.json');

function slug(value) {
  return String(value)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function assertInput(curriculum) {
  const errors = [];
  if (curriculum.schemaVersion !== 1) errors.push('schemaVersion must be 1');
  if (!curriculum.course || !curriculum.course.id || !curriculum.course.name || !curriculum.course.version) {
    errors.push('course id, name, and version are required');
  }
  if (!Array.isArray(curriculum.modules) || !curriculum.modules.length) errors.push('at least one module is required');
  (curriculum.modules || []).forEach((module, moduleIndex) => {
    if (!module || !module.id || !module.short) errors.push(`module ${moduleIndex + 1} requires id and short`);
    if (module && (!Array.isArray(module.objectives) || !module.objectives.length)) {
      errors.push(`module ${module.id || moduleIndex + 1} requires at least one objective`);
    }
    if (module && (!module.checkpoint || !module.checkpoint.id || !Array.isArray(module.checkpoint.options) || module.checkpoint.options.length < 2)) {
      errors.push(`module ${module.id || moduleIndex + 1} requires a valid checkpoint`);
    }
    if (module && module.checkpoint && (
      !Number.isInteger(module.checkpoint.answer)
      || module.checkpoint.answer < 0
      || module.checkpoint.answer >= module.checkpoint.options.length
    )) errors.push(`module ${module.id || moduleIndex + 1} checkpoint answer is outside options`);
  });
  return errors;
}

function manifestFromCurriculum(curriculum) {
  const modules = curriculum.modules.map((module) => ({
    id: module.id,
    short: module.short,
    objectives: module.objectives,
  }));
  const objectiveMap = curriculum.modules.flatMap((module) => module.objectives.map((objective) => ({
    objectiveId: objective.id,
    moduleId: module.id,
    checkpointId: module.checkpoint.id,
    diagnostic: false,
  })));
  return {
    schemaVersion: 1,
    course: curriculum.course,
    modules,
    finalQuizHost: curriculum.finalQuizHost === undefined ? null : curriculum.finalQuizHost,
    objectiveMap,
    presentation: {
      theme: 'default',
      layout: 'sidebar-left',
      customTheme: null,
      componentVariants: {},
    },
    components: { builtIn: ['diagram', 'objectives'] },
    engine: {
      required: true,
      entry: 'js/engine.js',
      capabilities: ['deterministic-randomness', 'rolling-statistics', 'random-walk', 'spaced-review'],
    },
    datasets: [{ id: 'demo', file: 'content/data/demo.json' }],
  };
}

function moduleMarkdown(module) {
  const objectiveList = module.objectives.map((objective) => `- ${objective.text}`).join('\n');
  const options = module.checkpoint.options.map((option) => `  - ${option}`).join('\n');
  return `---
title: ${module.short}
kicker: ${module.short}
subtitle: Generated by the course factory.
---

## Objectives

${objectiveList}

---

## Checkpoint

\`\`\`quiz
id: ${module.checkpoint.id}
objectives:
  - ${module.objectives[0].id}
q: ${module.checkpoint.q}
opts:
${options}
answer: ${module.checkpoint.answer}
expl: ${module.checkpoint.explanation || 'Generated checkpoint explanation.'}
\`\`\`
`;
}

function escapeHtml(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function copyRuntime(source, target, course) {
  fs.mkdirSync(target, { recursive: true });
  for (const entry of fs.readdirSync(source, { withFileTypes: true })) {
    if (entry.name === 'content') continue;
    if (!entry.isDirectory() && (entry.name === 'courses.html' || entry.name === 'courses.json')) continue;
    const sourcePath = path.join(source, entry.name);
    const targetPath = path.join(target, entry.name);
    if (entry.isDirectory()) copyRuntime(sourcePath, targetPath, course);
    else {
      fs.mkdirSync(path.dirname(targetPath), { recursive: true });
      if (entry.name === 'index.html') {
        const runtime = fs.readFileSync(sourcePath, 'utf8');
        fs.writeFileSync(targetPath, runtime
          .replace('learning-platform-template-theme', `${course.id}-theme`)
          .replace('<title>Learning Platform — Interactive Course Template</title>', `<title>${escapeHtml(course.name)}</title>`)
          .replace('📚 Your Course Name', `📚 ${escapeHtml(course.name)}`), 'utf8');
      } else if (entry.name === 'teacher.html') {
        const runtime = fs.readFileSync(sourcePath, 'utf8');
        fs.writeFileSync(targetPath, runtime
          .replace('<title>Teacher Progress Viewer — Your Course Name</title>', `<title>Teacher Progress Viewer — ${escapeHtml(course.name)}</title>`)
          .replace('🧑‍🏫 Your Course Name — Teacher Viewer', `🧑‍🏫 ${escapeHtml(course.name)} — Teacher Viewer`), 'utf8');
      } else if (entry.name === 'teacher.js') {
        const runtime = fs.readFileSync(sourcePath, 'utf8');
        fs.writeFileSync(targetPath, runtime.replace(
          "const COURSE_NAME = 'Your Course Name';",
          `const COURSE_NAME = ${JSON.stringify(course.name)};`,
        ), 'utf8');
      } else {
        fs.copyFileSync(sourcePath, targetPath);
      }
    }
  }
  if (source !== runtimeRoot) return;
  fs.mkdirSync(path.join(target, 'content'), { recursive: true });
  fs.mkdirSync(path.join(target, 'content', 'data'), { recursive: true });
  fs.copyFileSync(path.join(runtimeRoot, 'content', 'data', 'demo.json'), path.join(target, 'content', 'data', 'demo.json'));
}

function updateCatalog(course) {
  const text = fs.readFileSync(catalogPath, 'utf8');
  const lines = text.split(/\r?\n/);
  const result = [];
  let inserted = false;
  for (let index = 0; index < lines.length; index += 1) {
    if (lines[index] === `  - id: ${course.id}`) {
      index += 4;
      if (!inserted) {
        result.push(
          `  - id: ${course.id}`,
          `    name: ${course.name}`,
          `    version: ${course.version}`,
          `    manifest: courses/${course.id}/course-manifest.json`,
          `    route: courses/${course.id}/index.html`,
        );
        inserted = true;
      }
      continue;
    }
    result.push(lines[index]);
  }
  if (!inserted) {
    while (result.length && !result[result.length - 1].trim()) result.pop();
    result.push(
      `  - id: ${course.id}`,
      `    name: ${course.name}`,
      `    version: ${course.version}`,
      `    manifest: courses/${course.id}/course-manifest.json`,
      `    route: courses/${course.id}/index.html`,
    );
  }
  const nextText = `${result.join('\n').replace(/\n*$/, '')}\n`;
  fs.writeFileSync(catalogPath, nextText, 'utf8');
}

function main() {
  const inputPath = process.argv[2];
  if (!inputPath) {
    throw new Error('Usage: node scripts/course-factory.js <curriculum.json>');
  }
  const curriculum = JSON.parse(fs.readFileSync(inputPath, 'utf8'));
  const inputErrors = assertInput(curriculum);
  const manifest = manifestFromCurriculum(curriculum);
  const manifestErrors = validateCourse(manifest);
  const errors = [...inputErrors, ...manifestErrors.map((message) => `manifest: ${message}`)];
  const target = path.join(generatedRoot, curriculum.course.id);

  if (!errors.length) {
    fs.rmSync(target, { recursive: true, force: true });
    copyRuntime(runtimeRoot, target, curriculum.course);
    fs.writeFileSync(path.join(target, 'course-manifest.json'), `${JSON.stringify(manifest, null, 2)}\n`, 'utf8');
    curriculum.modules.forEach((module) => {
      fs.writeFileSync(path.join(target, 'content', `${module.id}.md`), moduleMarkdown(module), 'utf8');
    });
    updateCatalog(curriculum.course);
  }

  const generatedFiles = errors.length ? [] : [
    `courses/${curriculum.course.id}/course-manifest.json`,
    `courses/${curriculum.course.id}/index.html`,
    `courses/${curriculum.course.id}/content/${curriculum.modules[0].id}.md`,
    'courses.yaml',
  ];
  const report = {
    schemaVersion: 1,
    status: errors.length ? 'failed' : 'success',
    courseId: curriculum.course.id,
    outputRoot: errors.length ? null : path.relative(repositoryRoot, target),
    files: generatedFiles,
    validation: {
      input: inputErrors,
      manifest: manifestErrors,
    },
    warnings: [],
    generatedBy: 'template/scripts/course-factory.js',
    inputSha256: crypto.createHash('sha256').update(fs.readFileSync(inputPath)).digest('hex'),
  };
  fs.mkdirSync(path.dirname(reportPath), { recursive: true });
  fs.writeFileSync(reportPath, `${JSON.stringify(report, null, 2)}\n`, 'utf8');
  console.log(JSON.stringify(report, null, 2));
  process.exitCode = errors.length ? 1 : 0;
}

main();
